import {freshness,positionRun,preferReport} from './engine.mjs';
const $=id=>document.getElementById(id),map=L.map('map',{preferCanvas:true}).setView([1.35,103.82],12);
const tiles=L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© <a href="https://www.openstreetmap.org/copyright">OpenStreetMap contributors</a>'}).addTo(map);
const tracks=L.layerGroup().addTo(map),stations=L.layerGroup().addTo(map),trains=L.layerGroup().addTo(map),markers=new Map();
let data=null,live=null,bounds=null,selected='',urls=['../data/live.json'],loadingLive=false;
const paragraph=text=>{const p=document.createElement('p');p.textContent=text;return p;};
async function json(url,maxBytes=33554432){const response=await fetch(url,{signal:AbortSignal.timeout(12000),credentials:'omit',cache:'no-store'});if(!response.ok)throw Error('HTTP '+response.status);if(Number(response.headers.get('Content-Length'))>maxBytes)throw Error('Response too large');const reader=response.body.getReader(),decoder=new TextDecoder();let text='',size=0;try{while(true){const {done,value}=await reader.read();if(done)break;size+=value.byteLength;if(size>maxBytes)throw Error('Response too large');text+=decoder.decode(value,{stream:true});}}finally{await reader.cancel();}return JSON.parse(text+decoder.decode());}
function showNetwork(){tracks.clearLayers();stations.clearLayers();for(const line of data.lines)L.polyline(line.points,{color:line.color||'#aaa',weight:4,opacity:.8}).addTo(tracks).bindPopup(paragraph(line.name));for(const s of data.stations)L.circleMarker(s.point,{radius:3,weight:1,color:'#203445',fillColor:'#fff',fillOpacity:1}).addTo(stations).bindTooltip(paragraph(s.code+' · '+s.name));bounds=L.latLngBounds(data.lines.flatMap(l=>l.points));if(!map._networkFitted){map.fitBounds(bounds,{padding:[24,24]});map._networkFitted=true;}}
async function loadNetwork(){try{const next=await json('network.json');if(next.version!==1||!Array.isArray(next.runs)||!Array.isArray(next.patterns)||!next.shapes)throw Error('Invalid map data');if(!data||next.generated>data.generated){data=next;markers.clear();trains.clearLayers();showNetwork();const old=$('line').value;$('line').replaceChildren(new Option('All lines',''));const names=[...new Set(Object.values(data.routes).map(r=>r.name))].sort();for(const name of names)$('line').add(new Option(name,name));$('line').value=names.includes(old)?old:'';selected=$('line').value;}}catch(error){if(!data)$('status').textContent='Could not load the map. Please reload.';}}
function allowed(url){try{const parsed=new URL(url,location.href);return parsed.origin===location.origin||['https://hw737.user.srcf.net','https://raw.githubusercontent.com'].includes(parsed.origin);}catch{return false;}}
async function loadLive(){if(loadingLive)return;loadingLive=true;try{let best=null;for(const url of urls){try{const next=await json(url,4*1024*1024);if(!Number.isFinite(next.generated)||typeof next.live!=='boolean')continue;best=preferReport(best,next,Date.now()/1000);if(freshness(next,Date.now()/1000).predictions)break;}catch{}}live=preferReport(live,best,Date.now()/1000);}finally{loadingLive=false;}}
function tick(){const now=Date.now()/1000;$('clock').textContent=new Date().toLocaleString('en-SG',{timeZone:'Asia/Singapore',hour12:false})+' SGT';if(!data)return;const seen=new Set();let adjusted=0,count=0;const valid=now>=data.validFrom&&now<=data.validUntil;if(valid)for(const run of data.runs){if(selected&&data.routes[run.route].name!==selected)continue;const pattern=data.patterns[run.pattern],p=positionRun(run,pattern,data.shapes[pattern.shape],now,live);if(!p)continue;seen.add(run.id);count++;if(p.adjusted)adjusted++;let marker=markers.get(run.id);const color=data.routes[run.route].color;if(!marker){marker=L.circleMarker(p.point,{radius:5,weight:2,color,fillColor:color,fillOpacity:p.adjusted?1:.15}).addTo(trains);marker.bindPopup(paragraph(''));markers.set(run.id,marker);}marker.setLatLng(p.point);marker.setStyle({fillOpacity:p.adjusted?1:.15,color:p.adjusted&&p.delay>=60?'#e84b40':color});marker.getPopup().setContent(paragraph(`${data.routes[run.route].name} → ${run.headsign} · ${p.dwell?'At station':'Between stations'} · ${p.adjusted?'Operator-adjusted estimate'+(p.delay?' ('+Math.round(p.delay)+' s)':''):'Schedule estimate'}${run.computed?' · computed stop times':''}`));}
for(const [id,marker] of markers)if(!seen.has(id)){trains.removeLayer(marker);markers.delete(id);}$('count').textContent=count+' estimated trains';const fresh=freshness(live,now);$('status').textContent=!valid?'Schedule expired. Waiting for an updated timetable…':adjusted?`${adjusted} operator-adjusted estimates · ${count-adjusted} schedule estimates`:'Schedule estimates · fresh matching train predictions unavailable';$('alerts').textContent=fresh.report?(live.messages||[]).filter(x=>typeof x==='string').join(' · '):'';const bands=data.bands.filter(b=>now>=b.start&&now<=b.end&&(!selected||data.routes[b.route]?.name===selected));$('bands').textContent=[...new Set(bands.map(b=>(data.routes[b.route]?.name||b.route)+': about every '+Math.round(b.headway/60)+' min (individual trains not published)'))].join(' · ');}
$('line').addEventListener('change',()=>{selected=$('line').value;tick();});$('tiles').addEventListener('change',()=>{$('tiles').checked?tiles.addTo(map):map.removeLayer(tiles);});$('stations').addEventListener('change',()=>{$('stations').checked?stations.addTo(map):map.removeLayer(stations);});$('fit').addEventListener('click',()=>bounds&&map.fitBounds(bounds,{padding:[24,24]}));
await loadNetwork();try{const config=await json('../data/config.json',65536);urls=[config.live_url,config.fallback_url,'../data/live.json'].filter(u=>u&&allowed(u));}catch{}
await loadLive();tick();setInterval(tick,1000);setInterval(loadLive,30000);setInterval(loadNetwork,300000);
