[platformio]
default_envs = led

[env]
platform = espressif32@6.9.0
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags = -std=gnu++17
build_unflags = -std=gnu++11
extra_scripts = pre:scripts/select_config.py
lib_deps =
    bblanchon/ArduinoJson@6.21.5

[env:led]
build_flags = ${env.build_flags} -DENABLE_LEDS=1 -DENABLE_EPAPER=0
lib_deps =
    ${env.lib_deps}
    adafruit/Adafruit NeoPixel@1.12.3

[env:epaper]
build_flags = ${env.build_flags} -DENABLE_LEDS=0 -DENABLE_EPAPER=1
lib_deps =
    ${env.lib_deps}
    adafruit/Adafruit BusIO@1.16.2
    adafruit/Adafruit GFX Library@1.11.11
    zinggjm/GxEPD2@1.6.4
